# X=3
# Y=3

# print( X is Y)
# '''
# True BBecause they are in same memory object just point rom different variable
# '''

# x="shahan"
# y="shahan"
# print( x is y)


x="Hello-world"
y="Hello-world"
print( x is y)
# '''
# True BBecause they are in same memory object just point rom different variable
# '''

# x=[1,2,3,4]
# y=[1,2,3,4]

# print(x is y)
# '''
# False because they are same value list but different memory location or dierent object
# '''

# x=[1,2,3]
# y=x
# z=[1,2,3]

# print(x is y)
# print(x is z)
# print(y is z)


# x=[1,2,3,4]
# y=x

# x.append(5)

# print(x)
# print(y)

